# Generated by Django 4.2.3 on 2023-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, to='airport_service.crew'),
        ),
    ]
