# Generated by Django 4.2.3 on 2023-07-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0003_alter_airplane_options_alter_airplanetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'crew'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='airplane_type',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
