# Generated by Django 4.2.3 on 2023-07-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0005_order_alter_flight_crew_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='airport_name',
            new_name='name',
        ),
    ]
