# Generated by Django 4.2.3 on 2023-07-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0006_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
    ]
