# Generated by Django 4.2.3 on 2023-07-21 11:42

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("airport_service", "0007_alter_ticket_options"),
    ]

    operations = [RunPython(func, reverse_func)]
